# Generated by Django 2.2.5 on 2020-05-15 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_donate_organizationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
