# Generated by Django 2.2.5 on 2020-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='userprofilecore',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
